right_format = "$time"

[character]
error_symbol = "[â¯](bold red)"
success_symbol = "[â¯](bold green)"

[docker_context]
format = "via [ğŸ‹ $context](blue bold)"

[elixir]
symbol = 'î˜­ '

[git_branch]
symbol = 'î®¡ '
truncation_length = 20

[git_status]
conflicted = 'ó°‡ '
ahead = 'â‡¡${count} '
behind = 'â‡£${count} '
diverged = 'â‡• â‡¡${ahead_count} â‡£${behind_count} '
untracked = '?${count} '
stashed = '*${count} '
modified = '!${count} '
staged = '+${count} '
renamed = 'Â»${count} '
deleted = 'âœ˜${count} '
style = 'bold yellow'
format = '([$all_status$ahead_behind]($style) )'

[time]
disabled = false
style = 'white'
format = "ï€—[ $time ]($style)"
time_format = '%R'
